- nugu-client-kit/build.gradle
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/Channels.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/Options.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/core/GrpcServiceListener.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/core/GrpcServiceManager.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/core/RegistryService.kt
- nugu-core/build.gradle
Improved channels in transport
Add unauthenticated error handling
Remove kotlin-reflect
Remove unused code
> Improve transport

- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/net/HttpClient.kt
Removed the trustmanager code as it did not do any certificate validation
Incorrect implementation of the HostnameVerifier
> removed unsecure trust manager code

- app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
> Rename to GrantType

- app/src/main/java/com/skt/nugu/sampleapp/template/FragmentTemplateRenderer.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/client/DisplayAggregator.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/BaseDisplayAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTTSAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogUXStateAggregator.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/display/DisplayAgentInterface.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/tts/TTSAgentInterface.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayAggregatorInterface.kt
* add dialogRequestId at DisplayAgentInterface.Renderer.render
* add dialogRequestId at TTSAgentInterface.Listener's callback
* fix releated codes
> Map display and tts state change

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/client/DisplayAggregator.kt
If displayCardRendered called before render returned,
then displayCardRendererd call missed.
So, keep render request requestAgentMap first.
And lock it for thread safety.
> Catch missed render call

- nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
> Fix build error (#17)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDisplayAgent.kt
* TextList3, TextList4
* ImageList3
> Add missing types (#27)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultASRAgent.kt
Keep current audio provider to release.
> Fix audioRecord not released issue (#36)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/ExternalAudioPlayer.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/audioplayer/AudioItem.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/BaseDisplayAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTTSAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/common/payload/PlayStackControl.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/AudioPlayerDirectivePreProcessor.kt
Applied agents
* AudioPlayer
* AudioPlayer's template(display)
* TTS
* Display
> Apply playStackControl (#53)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTTSAgent.kt
This reverts commit 072e8ddc47d8c38d428e5cfa37492093474a5b0e.
> Revert "Just release sync at TTS stop (#55)"

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/ExternalAudioPlayer.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/AudioPlayStackProvider.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/DisplayPlayStackProvider.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
* Apply hold timeout(7sec) for sound context.
* Sound higher than Display if same priority.
> Follow context policy correctly (#55)

- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- nugu-login-kit/src/main/AndroidManifest.xml
- nugu-login-kit/src/main/res/values/styles.xml
- nugu-ux-kit/src/main/res/layout/item_chip.xml
- nugu-ux-kit/src/main/res/values/styles.xml
Rename Romain to Nugu
Remove unused strings
Add strings of setting
> Fix lint issues in resource

- versions.gradle
* keensense v0.1.3
** fix detection time
* silverTray v4.1.7
** fix wrong event send (IDLE->STOP)
> Update external library

- nugu-core/src/main/java/com/skt/nugu/sdk/core/sds/CircularBufferSharedDataStream.kt
* change isClosing to atomic
* double checking for isClosing
> Improve shared circulr buffer's thread wait (#119)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
1. Call startListeningWithTrigger once more at a short time
2. Except a last keywordDetectorInput created,
the others's close not called.
* Prevent to multiple call for startListeningWithTrigger
* Close reader when failed to startDetect for keywordDetector
> Fix missing call for reader's close (#120)

- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/client/DisplayAggregator.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/BaseDisplayAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/DisplayAudioPlayerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDisplayAgent.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/display/AbstractDisplayAgent.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/display/DisplayAgentFactory.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/common/EventCallback.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayInterface.kt
Manage setElementSelected as input process and
pass result to client through callback.
> Add callback for setElementSelected (#129)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSystemAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/connection/ConnectionManagerInterface.kt
* domain -> hostname
* hostname -> address
> Rename payload for handoffConnection (#131)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
> Fix not stop asr on busy (#133)

- versions.gradle
* Fix issue - TTS not stopped after stop called.
> Update silverTray to v4.1.8 (#137)

- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/client/DisplayAggregator.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/BaseDisplayAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/common/EventCallback.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayInterface.kt
* return dialog request id on requested
* throw IllegalStateException when receive invalid call.
> Return id for setElementSelected's request (#139)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
issue: startListening not work after stopTrigger called
cause: update state before detector's inactivation.
solution: update state after detector's inactivation.
> Fix startListening not work (#152)

- app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
- app/src/main/res/layout/remote_views_music_player.xml
Add margin in remote_views_music_player.xml
Fix json name from logo to iconUrl
> Icon not exposed in AudioPlayer.Template (#160)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/ASRAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/AudioPlayerAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DelegationAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DisplayAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/ExtensionAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/LightAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/LocationAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/MicrophoneAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/MovementAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/SpeakerAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/SystemAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/TTSAgentFactory.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/TextAgentFactory.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultASRAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDelegationAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDisplayAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultExtensionAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultLightAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultLocationAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultMicrophoneAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultMovementAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSpeakerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSystemAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTTSAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTextAgent.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/asr/AbstractASRAgent.kt
Factories need to inject agent at nugu client.
So it is correct to put 'client-kit'
> Move agent's factories to 'client-kit' package

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
Side effect for #164.
Create a single playSynchronizer.
> Fix issue - new playSynchronizer (#164)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/DisplayAudioPlayerAgent.kt
AudioPlayer stop after 10min of pausing.
So, the DisplayAudioPlayerAgent do not consider it anymore.
> Remove handling pause at display agent (#55)

- nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
> Improve timeUUID from v1 to v2 spec

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractCapabilityAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AbstractASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AbstractAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/delegation/AbstractDelegationAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AbstractDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/extension/AbstractExtensionAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/light/AbstractLightAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/microphone/AbstractMicrophoneAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/movement/AbstractMovementAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/AbstractSpeakerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/AbstractTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/AbstractTTSAgent.kt
current responsible for
1. directive handler wrapper implementation
2. context provide
* Move AbstractCapabilityAgent.kt to nugu-agent
* Change AbstractDirectiveHandler.kt to role(1).
> Divide resposibility for AbstractCapabilityAgent.kt

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
> Fix protocols to HTTP_1_1 in RegistryClient

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
> Remove duplicate post

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
* favorite command
* repeat command
* shuffle command
> Issue v1.1 audio player command (#193)

- app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
* multi-thread issue
* resource release timing
* custom state notify handler
> Fix issue for SpeechRecognizerAg (#200)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
> Fix invalid payload event (#211)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AbstractDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/BaseDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAudioPlayerAgent.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
* Remove visual focus manager
* Not focus management at display agent
> Discard visual focus management (#217)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
> Fix issue when create SpeechRecognizerAg (#229)

- publish-android.gradle
- publish.gradle
- versions.gradle
initial snapshot version : 0.8.3-SNAPSHOT
> Setup snapshot setting (#234)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/BatteryStatusProvider.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/battery/AndroidBatteryStatusProvider.kt
* add/implement isCharing API
* update isCharing context field
> Apply battery charing status (#238)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/EventMessageRequest.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
Change messageId from shortUUID to TimeUUID
> Fix a issue where the TimeUUID v2 spec does not apply (#172)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
When restart timer, apply duration at display.
> Apply duration of display payload (#263)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
AudioPlayer's pause directive not work.
Thread issue
* focus change
* directive handling
* play status change
To prevent too fast release of focus,
change the order in which directives are delivered.
Keep willBeHandleDirective to fix thread issue.
> Fix pause not work (#258)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioItem.kt
* add source type field
* play attachment
Update setSource() and release attachment.
> Play attahcment at AudioPlayerAgent (#236)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveGroupProcessorInterface.kt
On receive AudioPlayer.Play directive,
set display type to AudioPlayer always.
So, add listener at DirectiveGroupProcessor.
> Deliver display type correctly (#267)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
stop asr agent when receive notify result error.
> Handle notify result error (#272)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* Self-manage delayed timer for playSync & playContext.
* Not send stop event yet.
> Handle AudioPlayer.Stop directive on finish (#270)

- app/src/main/java/com/skt/nugu/sampleapp/template/FragmentTemplateRenderer.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerDisplayInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayInterface.kt
When display rendered, receive controller which can control display.
Move following APIs to controller
* controlFocus
* controlScroll
* getXXX()
> Divide display control API (#275)

- app/src/main/java/com/skt/nugu/sampleapp/widget/BottomSheetController.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
* add cancel flag which cancel asr processing or not.
> Support finish listening (#284)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/delegation/DelegationAgentInterface.kt
The data is missed when delegate's request.
Attach missed payload's fields.
* playServiceId
* data
> Attach missed payload at request (#286)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioItem.kt
* null value assign to source type.
Change to nullable, and if null handle it URL.
> Fix audio player not working (#288)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothEventBus.kt
Fix incorrect delivery of hasPairedDevices
Improve DiscoverableEvent
> Fix incorrect delivery of hasPairedDevices

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
1. Fix not play after animation stop
2. Add cancelAnimation
> Fix not play after animation stop (#209)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
> Send event with current context (#301)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/inputprocessor/InputProcessor.kt
To notify total, pass all not one by one.
> Pass all directives to input processor on receive

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/metadata/AudioPlayerMetadataDirectiveHandler.kt
Metdata is json object (not string)
Handle as failure if parse error.
> Fix data field type (#313)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
> Fix audioplayer stopped after 10s pausing (#320)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
> Fix wrong event name for setVolume/setMute (#322)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
when temporal pause -> explicit pause, send pause event.
> Send pause event correctly (#297)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
Change to access through the sdk container
> Modify access to the attahcment manager (#344)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Add directives following:
* Call1
* Call2
* Call3
> Support CallX directives for Display v1.2 (#341)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
set screen agent to state provider
> Fix screen's context not updated (#356)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt
Add to distinguish finish and stop.
> Add onStop at OnPlaybackListener (#369)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Player should release sync
when received stop directive on finished.
side effect for #332
> Fix not stopped audio player after finished (#374)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Crashed by SourceType=null
Change as nullable SourceType
> Fix audio player not playing for URL (#379)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Use callback instead of return to notify result.
> Add callback for request (#383)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
when multiply 2 at priority, occur overflow.
Chnage type from Int to Long.
> Fix overflow issue (#417)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
conversion should be occur before computation.
> Apply review (#417)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
return dialog request id for requestTTS
> Add missing return for requestTTS (#424)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
event listener for internal text source directive's handler
to notify
> Add event listener for text source handler (#420)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Only release owner(current)'s info and start next if exist.
> Fix not working previous command (#433)

- nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
usage :
val dialogRequestId = UUIDGeneration.timeUUID().toString()
val milliseconds : Long = UUIDGeneration.fromString(dialogRequestId).getTime()
> Extract time from UUID (#453)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/IntegratedMediaPlayer.kt
IntegratedMediaPlayer only delegate to active player (tts or audio).
Each player(tts, audio) manage each source id,
so will be conflict at IntegratedMediaPlayer.
> Manage sourceId for IntegratedMediaPlayer (#442)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt
From: use priority to order
To: use timestamp to order
> Manage playStack using timestamp (#458)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
> Fix DM not working

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
from: send event
to : stop media player
> Stop player when request stop by agent (#471)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogSessionManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/dialog/DialogSessionManagerInterface.kt
removed at ExpectSpeech's directive v1.1
> Remove field('property') at ExpectSpeech (#483)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
> Add missing RDRID

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Allow to use SpeechRecognizerAggregator without KeywordDetector.
> Allow to use w.o KeywordDetector (#473)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
> Allow empty token for display (#495)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
add display agent as state provider.
> Fix display context missed (#493)

- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
The credential have been cleared, but the cause is unknown
- Add some comment
- Change public access modifier, call setAuthorization directly.
> Bugfix/issue 432 (#432)

- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/view/DisplayAudioPlayer.kt
- app/src/main/res/layout/view_display_audioplayer.xml
If exist backgroundImageUrl at display's AudioPlayer.Template1/2, crash.
> Fix crash sample app (#501)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
This issue occurs because clients remain in the connection pool when WiFi is off.
> Disable connectionPool

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
To decide whether to resume or not, add playServiceId comparison.
> Add playServiceId comparison (#535)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
when filter context, include version only.
> Apply new context policy (#550)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* trim string before URI.create
* if occur exception, handle it as error
> Fix exception for URI.create (#555)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Cause
1. (A)'s template directive started & play sync started
2. (A) play directive started & play sync started
3. (B)'s template directive started, but just update
4. (B) resume directive started, and current item updated to (B) without
(A)'s finish
5. when receive stop onfinish state, just stop (B). So (A)'s play sync
not released.
Solve
Not update current item to (B). Keep (A) as current.
> Fix display not cleared after back/forward (#562)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogFocusHolderManager.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManager.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManagerImpl.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
*FocusHolderManager*
hold the focus if necessary
> Apply focus holder manager (#567)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/SoundProvider.kt
> Fix beepName from string to enum (Sound Interface)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt
> Waiting for Threads to Finish issue

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
On idle state, lyricsVisible not included at context.
> Fix missing lyricsVisible (#576)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Disable playcalled flag to not call stop() when not necessary.
> Fix player not started somethimes (#580)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
On resume,
from: keep prev directive as current
to: update current as current directive
> Update current directive always (#590)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
ensure thread-safety when access an eventStream.
> Fix crash for eventStream (#596)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerPlaybackInfoProvider.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
Reverts nugu-developers/nugu-android#589
> Revert "Feature/issue 588"

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlFocusDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlScrollDirectiveHandler.kt
* ControlFocus
* ControlScroll
> Fix wrong namespace for control events (#609)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
* ASR : 1.0 -> 1.1
* Delegation : 1.0 -> 1.1
* TTS : 1.0 -> 1.1
* Text : 1.0 -> 1.1
> Update agent version

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageInterpreter.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouterObserverInterface.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/DirectiveMessage.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageConsumer.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageObserver.kt
change interface(API) to receive message
> Optimize receive message passing

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
> Read directly at Attachment's reader (#624)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt
> Optimize read api to reduce cpu consume (#624)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManagerImpl.kt
Issue.
1. request recognition, but not state changed yet.
2. focus holder released.
3. asr release focus.
4. then, stop asr requested at 1.
Solve
when occur 2, we check recognition state(whether recognizing or not)
> Prevent unintentional stopping of recognition (#631)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
revert focus holder abandon -> request
> Fix audio player not play after tts finished

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageInterpreter.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/attachment/Attachment.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/AttachmentMessage.kt
remove a copy of attachment
replace toByteArray() to asReadOnlyBuffer()
> Optimize attachment write (#624)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
cancel directiveBeingPreHandled if match with dialogRequestId
> Cancel only matching directive

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
when ExpectSpeech does not matched with current session,
skip handling.
> Skip ExpectSpeech handling

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
delete: fill all buffer to zero value and set internal count
setLength: just set internal count
> Use setLength to resuse (#627)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
> Fix tts threading issue

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
> Deprecate timeoutInMillis at ExpectSpeech (#660)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Issue
* receive notify result directive
* receive response directive
* because threading sometimes, notify reuslt directive skip by response.
So, ensure it.
> Ensure execution order for directive

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
- versions.gradle
Update jademarble v0.1.9.
Lock start and state change of client speech processor.
> Fix expecting speech timing issue (#672)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/lyrics/AudioPlayerLyricsDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlayCommandDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/CloseDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlFocusDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlScrollDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ElementSelectedEventHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/playback/impl/PlaybackController.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/util/IgnoreErrorContextRequestor.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextRequester.kt
> Fix non-response for request (#674)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
should update template using sourceTemplateId
> Fix wrong templateId's update call (#684)

- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/EventMessageRequest.kt
Do not allow to change messageId.
> Create messageId after dialogRequestId (#688)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
If exist directive which be handle, do not release focus.
> Fix inproper focus release (#699)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
side effect from 932f85cb137d51daeed8e788ca6c83d6681a0407
> Fix resume not work after explicit pause (#707)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/AttachmentManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/attachment/AttachmentManagerInterface.kt
refresh timeout when receive an attachment.
remove timeout when receive the end attachment.
> Apply timeout for attachment (#714)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Problem
1. FocusHolder unholded
2. TTS request FocusHolder again
3. by 1, tts release focus.
4. TTS prepare current item to play
5. by 3, current item stop. <== this is a problem.
Solve
1. check focus changes, skip changes if not need.
2. improve focus release condition (if exist prepared info, do not
release focus)
> Fix tts not playing

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/SystemAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/handler/RevokeDirectiveHandler.kt
> Add WITHDRAWN_USER reason at System.Revoke (#723)

- versions.gradle
> Update keensense v0.2.1

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/OsContextProvider.kt
* Create OsContextProvider
* Setup Android OS context
> Apply client's os context (#747)

- app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
- app/src/main/res/values/strings.xml
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/exception/BaseException.kt
https://developers-doc.nugu.co.kr/nugu-sdk/authentication
> Add code to NuguOAuthError (#817)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Contact.kt
> Update ContactObject of MessageAgent (#827)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Deactivate a session on cancelling ASR.EXPECT_SPEECH.
> Fix the session not deactivated (#835)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
If the session activated before set, do not schedule timeout.
> Fix invalid session timeout (#838)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Handle as stop if stop called even if player finished.
> Improve audio player's stop (#832)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* update version to 1.4
* add playServiceId at Context
> Support AudioPlayer v1.4 (845)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
* min/max volume.
* defaultVolumeStep
* mute
> Allow nullable field of volume context (#863)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
* change address as object.
* add businessHours.info field.
> Update Person object (#865)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
* update agent version v1.2
* add defaultVolumeLevel, group context.
> Support Speaker Interface v1.2 (#874)

- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
* Fix wrong sample's usage for repeat API.
> Rename shuffle/favorite/repeat API (#881)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
* getCandidateList -> sendCandidates (sync->async)
> Change API of MessageClient (#885)

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
> Fix incorrect state processing (v1)

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/context/PlayStackContextManagerTest.kt
* Fix wrong order.
* Write test code.
> Fix reverse order of playstack (#889)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
* update getContext API with given context.
> PhoneCall.CandidatesListed with full context (#880)

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Problem
1. The ASR is in THINKING.
2. The trigger start.
3. The SpeechRecognizerAggregator's state is WAITING.
4. If SpeechRecognizerAggregator's stop called, only stop the trigger. <= Should stop the ASR also.
> Fix not stop listening on working (#904)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouterInterface.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/connection/ConnectionManagerInterface.kt
> Add the ResetConnection and Noop directive

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallClient.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/BlockIncomingCallDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/BlockIncomingCallPayload.kt
* BlockingIncomingCall -> BlockIncomingCall
> Fix wrong directive name (#931)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
* finish the play sync based on:
* dialogRequestId -> dialogRequestId and playServiceId.
> Update the policy of the playSync (#914)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
when focus foreground, resume if
* no playback directive to handle
* bt paused
> Fix BT streaming & focus issue (#939)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Release focus, when tts stopped or finished:
before: immediately
after: after response received for event.
> Improve tts's focus release logic (#936)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
if stop called, do not set 'errorTypeForCausingEpdStop'.
> Fix invalid asr result (#965)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
* Notify only when setState() if something changed.
> Simplify dialogUX notify logic (#994)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/Channel.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/ChannelTest.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizerTest.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
* Separate priorities for acquire and release
(Remove volatile property)
* ASR has top priority for acquire except DM ASR.
* ASR, DM ASR has the lowest priority for release.
> Update the priority of focus #1012

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
When the ASR state changes from non-BUSY to IDLE,
update the state for dialogUX immediately.
> Update DialogUX's state immediately #1034

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
* Release playSync on TTS stop/finish immediately.
* Release focus afterTTS stop/finish event.
> Improve focus & playSync management for tts #1043

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
When the audio player resumed,
send templateId correctly at AudioPlayerAgentInterface.Context.
> Send templateId for AudioPlayer correctly #1057

- nugu-core/src/main/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerImpl.kt
Do not clear display when start a play with same playServiceId.
> Fix wrong layer policy issue #1067

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Contact.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
* Add EMERGENCY value at Contact.Type
> Apply Message Interface v1.2 #1072

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
> Change maximum number of texts in the chips (#1103)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
After setHandlingComplete, handler's cancel directive not work.
> Fix not cancel ASR.ExpectSpeech from PlaySync#1110

- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
* Fix SeamlessFocusManager's focusHolder not release focus,
after ASR.DM
> Fix focus not release issue #1118

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
Cancels the job of release that posted before acquire.
> Fix invalidated release for FocusInteractor #1127

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
In some device, response receive before onRequested called, so pre call finish before send last attachment.
> Fix thread issue for asr callback #1138

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
To know exact prev focusState.
> Not change focusState immediately #1138

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
- nugu-agent/src/test/java/com/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayloadTest.kt
* Add searchTargetList at SendCandidates
> Support PhoneCall 1.1 #1145

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Ensure execution for blocked directive
before next tts handle requested.
> Return TTS's prehandle after finish current #1149

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/UpdateDirectiveHandler.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
If receive Display.Update(B) for display(A) and Session.Set(B),
hold Session.Set(B) until display(A) cleared.
> Apply hold session while Display.Update #1146

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
* Add UnifiedSearch1 Directive
> Support Display Interface v1.6 #1171

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
* call stop without condition check.
> Fix not working stop trigger #1175

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
* Call onRecieveTTS only if acquire focus success.
> Fix not return to idle state of DIalogUX #1182

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageDispatcher.kt
* rename MessageInterpreter -> MessageDispatcher : does not interpret
anymore.
* Add to Sdkcontainer for free access.
> Allows to receive messages from any module #1197

- app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
> Fix to run without login if token has not expired #1203

- versions.gradle
* keensenese : 0.2.2 -> 0.2.3
* jademarble : 0.2.0 -> 0.2.1
> Update libs #1207

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
* only stop epd when background focus
> Fix wrong stop ExpectSpeech #1218

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/AudioSourceManager.kt
Reverts nugu-developers/nugu-android#1239
> Revert "Prevent closing AudioSource while read #1185"

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
* Fix IllegalMonitorException at unlock() when onLoop().
> Lock more finely #1280

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
* Apply SearchScene field
* Add recipient field at context
* Deprecate SearchTarget
> Support PhoneCall v1.2 #1292

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Context.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/payload/SendCandidatesPayload.kt
* Add searchScene field at SendCandidates directive and Context
> Support Message Interface v1.3 #1300

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/Chip.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
> Support Chips Interface v1.1

- versions.gradle
* Jademarble v0.2.2
* Keensense v0.2.4
> Update library #1313

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/MakeCallDirectiveHandler.kt
> Support PhoneCall v1.2 #1317

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
* Solve focus change threading issue :
change request from per agent to per directive
> Fix tts's focus thread issue #1322

- app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateExtension.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ThrottledOnClickListener.kt
1. Implement ThrottledOnClickListener
2. Apply sample app #1331
throttleInMillis(1000L) has yet to be confirmed.
> Implement ThrottledOnClickListener

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Send TTS's playback event even if the playServiceId is empty or null
> Support TTS Interface v1.3 #1343

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
* If no handler for directive, notify it as onFailed
> Add missing noti for directive failure #1355

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
- versions.gradle
* Support audioAttributes instead of streamType
> Update SilverTary v4.3.0 #1357

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
* Apply epd param of ExpectSpeech
> Support ASR v1.4 #1372

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
* Apply 10sec for every timeout for context except ASR.Recognize event.
(keep 2sec for ASR.Recognize event)
> Update context timeout policy #1375

- app/src/main/java/com/skt/nugu/sampleapp/template/FragmentTemplateRenderer.kt
- app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerDisplayInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
* at DisplayAgentInterface.Renderer.render()
* at ASRAgentInterface.OnResultListener's callback
> Replace dialogRequestId to header #1393

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/session/SessionAgent.kt
* Send recent session, if exist same playServiceId session.
> Update session management #1398

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/session/SessionAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
* Send recent session correctly
> Fix issue-1398 #1427

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Keep the screen on when ASRAgent is progressing
> Add setScreenOnWhileASR method to keep the screen on #1416

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/LogSettings.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
- versions.gradle
> Enable/Disable external lib log #1432

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
* Send TextSourceFailed event
* Send TextRedirectFailed event
> Support Text Interface v1.5 #1403

- nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
* Fix wrong duplicated removal check
> Fix issue-1427 #1437

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/utility/handler/BlockDirectiveHandler.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/BlockingPolicy.kt
* Utility.Block directive should be blocked by all medium
> Fix Utility.Block's blocking policy #1446

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
> Support AudioPlayer v1.5 #1448

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
* Call missing onError for SpeechRecognizer.startListening.
> Call missing callback #1452

- app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
* Int is also reference
* omission of updating sourceId
> Fix ExoMediaPlayer doesn't calling onRetrieved callback

- app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/SampleTemplateHandler.kt
- app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
fix several issues and improve.
- Fix crash when request Podcast during Podcast
- Fix an issue that the start/end time was displayed in a play without duration. (ex.radio)
- ~~Fix an issue that media duration not notified~~ (previous other commit already fix this)
- set userWideViewPort 'true'
- add display interaction notifying
> Improve TemplateView

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- release audio player listener when Activity destroyed
- release lyricsPresenter from DefaultAudioPlayerAgent when view detached from window
> Fix memory leak in SampleApp

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
Add Custom TemplateView Constructor
> Add Custom TemplateView Constructor

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
* register tts agent at InterLayerDisplayPolicyManager as listener
> Add missing listener registration #1537

- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
* not working focus manager when an external focus interactor not set
> Fix not working focus manager #1535

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* remove waitPlayExecuteInfo from willBeHandleDirectives
even if not handled yet.
> Fix not playing audio player sometimes #1544

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
- combine similar functions
- formatting
- remove unnecessory function call
- remove not working function call
- add block that remove item from map if there's no value.
(in clearDirectiveBeingHandledLocked() function.)
- use clone() function for copy queue
> Trim source code.

- build.gradle
- publish-android.gradle
- publish.gradle
- versions.gradle
when publish snapshot build, set
* isReleaseMode=true
* publishSnapshot=true
> Simplify snapshot build #1550

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* remove waitFinishPreExecuteInfo when canceled.
* remove canceled wawitPlayExecuteInfo
> Fix not playing or stopping sometimes #1544

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/PlaybackDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/DirectiveGroupHandlingListener.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/TimeoutResponseHandler.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveGroupPreprocessor.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveGroupProcessorInterface.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveSequencerInterface.kt
- typo
- redability
- combine DirectiveGroupProcess Listener callback for redability
- remove unnecessory new object creation in logic
> Trim the code

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
* To prevent client's miss, ignore multiple call.
> Handle multiple displayCardRendered call #1557

- build.gradle
- versions.gradle
* Timestamp changed when build each module, so type it as static.
> Type timestamp by hand #1550

- nugu-client-kit/build.gradle
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/MessageRequestConverter.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/ProtobufExtensions.kt
> Change UnsafeByteOperations to ProtobufExtensions with protobuf-javalite dependency issue

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveRouter.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveSequencer.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveSequencerInterface.kt
> Trim the code.

- app/proguard-rules.pro
> Update proguard-rules #1570

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
* side effect for #1562(Fix wrong access at AudioPlayerTemplateHandler's templateDirectiveInfoMap)
> Fix wrong cancel for AudioPlayerTemplate #1588

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
* The audioplayer notify whether render or update
> Fix sync for update and resume #1592

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
* To distinguish SPEECH_END and a completion for ASR, add Idle state.
> Add Idle state at SpeechRecognizerAggregator #1601

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
* When an attachment is sent too late(after timeout),
ASR.Recognize event occur timeout.
In this case, stop current ASR recognition.
> Handle timeout issue for ASR.Recognize event #1603

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
* Call getContext from another thread.
* Apply multi-thread
> Improve getContext API #1611

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/res/drawable/nugu_lyrics_button_bg.xml
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer.xml
- nugu-ux-kit/src/main/res/values/styles.xml
Design spec changed - remove newly added design
> Combine LyricsButton Design

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSScenarioPlayer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizerTest.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
Add default function in Interface
Change function to value
Remove DUMMY_PLAY_SYNC_CALLBACK
> Trim the code in SynchronizeObject and OnRequestSyncListener interface.

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/RenderDirective.kt
> Support Chips Interface v1.2 #1583

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateExtension.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
Fix qa issue (NUGUSDKQA-42)
Fix qa issue (NUGUSDKQA-38)
Fix QA issue (NUGUSDKQA-24)
Fix qa issue (NUGUSDKQA-45)
> fix qa issues

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
> Fix qa issue(NUGUSDKQA-46)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
* Track events that causes the cancellation only when a current routine is playing.
> Fix routine canceled incorrectly #1668

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml
Add default divider to bar type player.
Sync setting between normal type player and bar type player.
> Fix QA Issue(NUGUSDKQA-40)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/nudge/NudgeAgent.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml
> Fix QA Issue(NUGUSDKQA-29)

- build.gradle
- javadoc-android.gradle
- javadoc.gradle
Reverts nugu-developers/nugu-android#1685
> Revert "Update dokka 0.10.0 -> 1.4.30 #1684"

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
* Support resume, pause, stop API
* Support status callback API
> Support public API for RoutineAgent #1701

- build.gradle
- versions.gradle
* refer system variable to build if exist
> Setup build environment

- nugu-ux-kit/build.gradle
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateViewModel.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
-String Escape Util have removed due to server doesn't send payload which contains backslash anymore.
-Fix issue when orientation changed after Display.Update directive on Radio List Template, the list would be empty.  
(fix logic merging update template payload to original template)
> Remove Escape Util

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/Chip.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
test and design confirm not done yet
> Add Nudge to Chips Type

- app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingHeadWindow.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
> Support ASR Interface v1.6

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/BasicTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
-FLOSDKEAA-159, 
-After orientation change, button doesn't work because fragment reference is cleared by gc.
> Fix QA Issue

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/nudge/NudgeAgent.kt
issues.
- data type was string instead object
- compact context was mutable
> Fix NudgeInfo Bug

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Previous updateChips() method can conflict NUGU basic spec.
So CustomChipsProvider which request custom chips only when it's available is needed.
> Add CustomChipsProvider Interface

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
> Fix crash #1818

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/TemplateNativeView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
1.Fix issue that some button(collapse, close) not working after layout change
2.Fix memory leak when next media played
> Fix mediaTemplate issues

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
https://tde.sktelecom.com/pms/browse/NUGUSDKQA-122?filter=-1
> Fix media template info bug

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
> Fix media template time info bug when radio playing

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClientInterface.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/theme/ThemeManager.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/theme/ThemeManagerInterface.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
UI work is not done yet.
ThemeManager is interface to make App can set Theme.
> Add ThemeManager to apply theme

- app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
* Remove deprecated functions
* Fix when statement warning (does not explicitly include all the values)
> Improve ExoMediaPlayer

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Reverts nugu-developers/nugu-android#1780
> Revert "Clear chips at IDLE state #1779"

- build.gradle
Add test option to prepare CI setting
> Add test option

- app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/EventsService.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
- nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthTest.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
make parameter name same with super
> fix lint error

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/theme/ThemeManager.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateUtils.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/JavaScriptHelper.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
plus, fix malfunction when media type template shown on WebView.
> Apply theme to web template

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/BatteryStatusProvider.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/DefaultBatteryAgent.kt
* add approximateLevel for context
> Support Battery Interface 1.1 #1865

- nugu-service-kit/build.gradle
- nugu-service-kit/src/androidTest/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebViewTest.kt
- nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
1. Change the setCookie parameter url to host
2. Add test code
> Change the NuguWebView setCookie url to host #1891

- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
There was leak which hold LoginActivity object.
> Fix OnLoginListener Memory leak

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/BasicTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/controller/BasicTemplateHandlerTest.kt
NUGUSDKQA-153
Add interface to allow app to set custom template handler
> Make App can custom action when template touched

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
> Add template onStart() call back to Listener

- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
- nugu-ux-kit/src/main/res/layout/view_item_lyrics.xml
I've applied wrong layout before. 
Lyrics View should be small when landscape rather than full screen size.
> fix LyricsView layout  on landscape

- app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
reason:
Template render noti not sended.
because, There was an erorr before loading complete.
fix:
Change render noti must sended even if there were errors before loading complete.
> Fix issue that TTS not played.

- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandlerTest.kt
Add Exception Handling of using Enum valueOf() method
> Add DefaultTemplateHandler TestCode

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
> Support Display Interface v1.8 #1965

- nugu-ux-kit/build.gradle
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateViewTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragmentTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsViewTest.kt
with setting that makes Robolectric run
> Add TemplateFragment Test 

- build.gradle
- nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
- versions.gradle
* kotlin 1.4.32 -> 1.5.20
* silvertray 4.3.6 -> 4.3.7
> Update library #1974

- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
> Edit Landscape Media Template layout

- nugu-ux-kit/build.gradle
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
OPENSDK-91
-Add interface
-Apply it synchronously to template
> Add Nugu Button color setting interface

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
* If setSource called on READY or STARTED, reset player.
> Reset tts player if need #2001

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidContextDummyFocusInteractorFactory.kt
* If the other player is playing
> Pause AudioPlayer explicitly #1996

- app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/handler/ContinueDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/handler/StartDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
* start directive control
* continue directive control
> Add interface to control routine's directive #2008

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
COSTELTV-83
It was applied only on NativeView before.
> Apply logic that restore previous render info on webView media template.

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/CloseDirectiveHandler.kt
* Complete directive handling when display closed or failed.
> Change complete timing for Display.Close directive. #2044

- nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/attachment/Attachment.kt
* remove hasCreatedReader()
* remove hasCreatedWriter()
> Remove Attachment's unused API #2056

- jacoco.gradle
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguButton.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguSnackbar.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguButtonTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguSnackbarTest.kt
+ exclude NuguFloatingActionButton which is deprecated
> Add nugu widget test code

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* (AudioPlayer) Handling stop after finished.
> Fix side effect for #2001 #2077

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateContextTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayerTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebViewTest.kt
> Add WebTemplate test code 

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
* change ASR's state from enum to sealed class
* Not render nudge chips if ASR(DM) not initiated by ExpectSpeech directive.
> Apply Nudge Chips Policy #2086

- nugu-core/src/test/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManagerTest.kt
* Increase timeout for verification
* Call verify at the other thread.
> Reduce test failure

- nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
* access cached state with ContextType
* log the time taken which to get state
> Refactor context manager

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
- app/src/main/java/com/skt/nugu/sampleapp/activity/main/CustomMediaTemplate.kt
- app/src/main/java/com/skt/nugu/sampleapp/activity/main/CustomTemplateHandler.kt
- app/src/main/java/com/skt/nugu/sampleapp/activity/main/MainActivity.kt
- app/src/main/java/com/skt/nugu/sampleapp/service/SampleAppService.kt
- app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingHeadWindow.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/custom_media_player.xml
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateNuguHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/TemplateNativeView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/MediaTemplateResources.kt
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
- nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateNuguHandlerTest.kt
And add example code.
[AISRVDEV-325](https://tde.sktelecom.com/pms/browse/AISRVDEV-325?filter=-1)
> Change implementation of DisplayAudioPlayer to let  client derive.

- app/src/main/java/com/skt/nugu/sampleapp/activity/main/CustomMediaTemplate.kt
- app/src/main/res/layout/custom_media_player.xml
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/MediaTemplateResources.kt
- nugu-ux-kit/src/main/res/drawable/nugu_album_cover_bg.xml
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml
- nugu-ux-kit/src/main/res/layout/view_lyrics.xml
- nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml
- nugu-ux-kit/src/main/res/values/colors.xml
- nugu-ux-kit/src/main/res/values/styles.xml
For now the custom of MediaTemplate is not support dark theme.
> Change coloring logic on LyricsView for making it easy to custom it

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgent.kt
* handle EmptyStackException which peek throws.
> Fix side effect for #2159

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
> Support PhoneCall v1.3 #2169

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateMediaHandler.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateMediaHandlerTest.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsViewTest.kt
https://tde.sktelecom.com/pms/browse/APOLLOQA-145
> Improve LyricsView update performance

- app/src/main/res/layout/custom_media_player.xml
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
- nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml
https://tde.sktelecom.com/pms/browse/AISRVDEV-419?filter=-1
The issue is small lyrics view is not support Text size changing becuase of it's parent has fixed height.
So parent of it become WRAP_CONTENT SIZE. 
And for this,  this PR have change small lyrics view to only have 2 items in their recycler view .
> Apply dynamic measure to small lyrics view

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveRouter.kt
* Iterating of Collections's synchronizedSet does not thread-safe.
* Use lock explicitly.
> Fix Exception at DirectiveRouter #2186

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveRouter.kt
- nugu-core/src/test/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveRouterTest.kt
* Reduce getDirectiveHandler API call
> Improve directive handling

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidContextDummyFocusInteractorFactory.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AudioFocusInteractorFactory.kt
* Select handler thread when request android audio focus.
> Add feature at AndroidAudioFocusInteractor #2189

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/DirectiveGroupHandlingListener.kt
> Fix NPE #2200

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgent.kt
* Exclude myself from comparison.
> Improve parent&child display check logic #2202

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Contact.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
* Add "SAVE_CONTACT", "BLOCK" intent type.
* Add "numberBlockable" field at Context.
* Add "isBlocked" field at Contact Object.
> Update PhoneCall v1.3 #2208

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/InteractionControl.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/GetMessageDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgent.kt
* Append interaction control payload at event
> Update InteractionControl Policy #2211

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Contact.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
- nugu-agent/src/test/java/com/skt/nugu/sdk/agent/ext/ContactTest.kt
* isBlock is boolean, serialize as string
> Fix PhoneCall's Contact Serialization #2220

- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
https://tde.sktelecom.com/pms/browse/APOLLOTF-360
> Change description parameter of UnAuthenticatedException from required to optional

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSource.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSourceAboveQ.kt
* from:unregisterAudioRecordingCallback->stop->release
* to:stop->unregisterAudioRecordingCallback->release
> Change unregisterAudioRecordingCallback timing

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
> Add option for audiofocus request

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguVoiceChromeView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
* just log on failure.
* TODO : fix correctly.
> Fix lottie exception #2252

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
* Save current offset before pause or stop.
* Get offset if player is active.(If the player is inactive, the player's
offset is undefined)
> Manage an audio player's offset at agent #2250

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/AudioSourceManager.kt
* Add a listener to get audio buffer read from audio source
> Get audio buffer written at stream #2255

- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
* Allow selection of focusGain to use in AndroidAudioFocusInteractor
> Add focusGain property #2279

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
* Prevent the transition state from STOPPED to INTERRUPTED (Routine cannot be paused after canceled)
> Fix wrong routine state #2283

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/handler/StartDirectiveHandler.kt
* At StartDirective, Context, 
** add routineId, routineType field.
> Routine Interface 1.3

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/permission/RequestPermissionDirectiveHandler.kt
- nugu-agent/src/test/java/com/skt/nugu/sdk/agent/permission/RequestPermissionDirectiveHandlerTest.kt
* FROM: blocked by AUDIO => TO: non blocked
* remove unused import
> Change RequestPermission's Blocking Policy #2290

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
> Fix wrong spelling check

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
* Call tryStartNextAction API after last action finished even if tryStartNextAction flag is false.
> Fix not finish routine

- app/src/main/java/com/skt/nugu/sampleapp/activity/main/CustomMediaTemplate.kt
- app/src/main/res/layout/custom_media_player.xml
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
Change way to set custom media template resources from overriding val to providing as parameter.
> Change way to set custom media template resources

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
- nugu-ux-kit/src/main/res/drawable/bg_round_blue.xml
- nugu-ux-kit/src/main/res/layout/view_lyrics.xml
- nugu-ux-kit/src/main/res/values/styles.xml
Add font scale button on Lyrics. 
and
few refactoring
> Add font scale button on Lyrics

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateViewModel.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistAdapter.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayerTest.kt
and
Implement update playlist.
Clear playlist fragment when data cleared.
> Update Playlist data model

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playlist/PlaylistMerger.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
- nugu-ux-kit/src/main/res/layout/nugu_fragment_playlist.xml
- nugu-ux-kit/src/main/res/layout/view_lyrics.xml
- Fix list cleared issue when updatemeta without list is received.
- Add ElementSelected event callback
- Remove change animation of playlist RecyclerView
and
Fix LyricsView layout issue that last lyrics view item is rendered patially
> Playlist implementation

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
and avoid crash when list item clicked during media template replaced new one
> Fix ElementSelected Event not sent

- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistAdapter.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
and, Add diff util when update all list
> Scroll to current playing position on Playlist

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
* receiving a response to a request to pause a routine
* (this is not a spec)
> Do not cancel the routine when (#2376)

- app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/CSRFProtection.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/OnceLoginListener.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/exception/BaseException.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/extention/JsonExtensions.kt
- nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
- nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthTest.kt
- nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivityTest.kt
1. Update NuguOAuth class to object
2. Separate classes of CSRF-related code
3. Separate the appendDataToJson code
4. Separate the OnceLoginListener code
5. Add the UserCanceledException to BaseException
6. Add debug logs
> Update NuguOAuth class to object

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/image/ImageAgentImpl.kt
* Send null when attachment is end.
* Send event & data at sender thread.
* Send data after event success.
* Call onImageSendFailed also when event failed and image retrieve failed.
* Send attachment on sequentially.
> Improve and Fix ImageAgent #2403

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/image/ImageAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/image/ImageAgentImpl.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
* Send Image.ImageSend as async to avoid timeout.
* Improve&Comment SendImageCallback.
> Fix Image.ImageSend event's timeout #2403

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
> Apply TextInput's source for Routine #2424

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
* Provides stop API that does not cancel "ActionTimeoutTriggered" event
> Provides stopSoftly API at RoutineAgentInterface #2431

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playlist/PlaylistPresenter.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playlist/ShowPlaylistDirectiveHandler.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
* Manage visibility of playlist
> Implement AudioPlayer 1.8 spec #2433

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransport.kt
- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/RegistryClient.kt
[DEVICEGW-3334](https://jira.tde.sktelecom.com/browse/DEVICEGW-3334)
> Fix sid change issue in registry progress

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/image/ImageAgentImpl.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgent.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
* ASR v1.8
* Text v1.8
* Image v1.1
> Update Interface Version

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
* 'acquire audio stream' does not released
* (687feab0)
> Fix side effect for #687feab0

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
* Append 'aiPhoneUserId' at context
> Support PhoneCall v1.4 #2459

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayerTest.kt
* Add "libraryAvailable" field
* Update AudioPlayerAgent v1.9
> Support AudioPlayer v1.9 (#2463)

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
* Append epd param at ASR.Recognize event
> Support ASR v1.9 #2465

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
- nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/model/TemplateModels.kt
- nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayerTest.kt
* Add "badgeButton" field at AudioPlayer.Template1's metadata::template::content
> Support AudioPlayer v1.10 #2468

- nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
* Use dialogRequestId or asyncKey's eventDialogRequestId
> Properly handle blocking key

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
* Finish ASR when receive first directive.
* Not block AUDIO policy directive on ASR.
> Revert asr's finish and directive blocking policy

- nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
* Addable new channel configuration
> Configure custom 'FocusChannelConfiguration' #2504

- nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
- nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
* Try acquire external focus before set foreground focus
* If failed to acquire external focus, set focus as foreground or background according of setting.
> Improve a focus acquire logic #2517

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/DefaultTTSAgent.kt
* Make the text field of speak payload optional
> Support TTS v1.4 #2533

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/DirectiveGroupHandlingListener.kt
- nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
* Handle as error on ASR Agent
> Handle System's "ASR_RECOGNIZING_EXCEPTION" #2535

- publish-android.gradle
- publish.gradle
* allowInsecureProtocol = true
* with sourceJar,javadocJar
> Fix publish script

- build.gradle.kts
* extra should be set before apply vesrsion.gradle.kt
> Fix error on publish snapshot

- nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/DefaultTTSAgent.kt
> Fix codec value #2552
