nugu-developers/nugu-android

nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt

Prevent to call playbackStopped() without playbackStarted()

Fix tts blocking issue (#79)

---

nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayInterface.kt

Set null to setElementSelected's callback as default.

Set default value

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogUXStateAggregator.kt

Prevent transit to IDLE state on preparing tts.
(use onReceiveTTSText() to check tts preparing)

Fix invalid transit to IDLE state (#154)

---

nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt

If enter to ENDED after READY without STARTED,
call onPlaybackStarted().

Fix invalid opus player status change (#157)

---

app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

add notifyOnReleaseAudioInfo() to remove duplication.
== Cause (example)
1. executeStop(true)
2. onPlaybackStopped(id=1)
3. executePlayNextItem()
<== current source id changed(id=2) and next item became null.
4. executeOnPlaybackStopped(id=1)
<== id 1 and 2 not equal. so event skipped.
== Solution
Do not call executePlayNextItem.
The next item will be play after stop finished by executeStop(true).

Fix not notify audio player state changes (#194)

---

nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt

Not safe at :
1. If compareAndSet(false, true) success and state is ACTIVE,
then keyword detector do not executed. But flag set to true already.
So, cannot execute keyword detector anymore.
2. AtomicBoolean's set not atomic operation(just volatile)

Fix isStartListeningWithTrigger flag (#196)

---

nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/sds/CircularBufferSharedDataStream.kt

If reader start to read buffer after writer closed,
reader wait and not notified forever.
so, we check buffer full(writer closed or not) before wait.

Fix issus for blocking at SDS'reader (#211)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt

Sometimes, TTS's prepareSync called
after display's startSync finished.
So, early call prepareSync of TTS.

Fix display cleared while TTS speaking (#226)

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt

Revert following:
To prevent too fast release of focus,
change the order in which directives are delivered.
Why: Because the InputProcessorManager manage request and response,
should receive directives before request sequencing.
Issue(Too fast release of focus) should be solve by other way.

Revert #258 partially.

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt

side effect for #284
If client request to finish listening(complete asr) before SPEECH_START,
we handle it as just like stop listening(cancel asr).
In case of client epd, nothing to complete asr request.

Fix voice chrome not dismissed (#317)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt

Issue:
1. asr acquire focus
2. audio player go to background and paused.
3. when asr finished (receive response), asr release focus
4. audio player become foreground.
5. audio player try to resume current item.
Solve:
Audio player look into received response before become foreground.
If exist AudioPlayer's playback directive in received response,
do not resume.

Fix wrong resume issue on focus change (#266)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

side issue for #297
Use playerActivity instead of currentActivity
to determine the context update policy.

Fix audio player context not updated (#333)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt

If release focus immediately after tts finish,
can be occur temporal focus changes.
To prevent it, release focus of tts when dialog state became IDLE.

Prevent focus loss between DM and TTS (#346)

---

nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt

RawCBRStreamSource use a global thread to read & write.
In case of a player paused, the player will not read and a thread
blocked (waiting to finish read).
When the other player try to start read, it will not be started forever.
So, we use a new thread per instance.

Fix tts player not work using two or more (#384)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt

Refactor a way to get play context.
Changes
from : Each agent update the play context when changed.
to : The manager ask current play context to each agent if necessary.

Apply observer to gather play context (#393)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt

Close directive's complete handling missied.
So, after close directive received,
all blocking directives was blocked.

Fix close directive not completed (#408)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt

Except for CustomTemplate, all directives must have a token.

Strictly check token for render directives (#449)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt

Issue
if occur error before tts playing, dialogUXStateAggregator never return
to idle state.
Solve
notify error for tts to try return idle state.

Handle tts error correctly (#518)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

We check the player status before request stop.
However if exist fetched and play
called item, it will be playing even if loss focus.
So, we request stop always when loss focus without the status check.

Stop audio player when loss focus always (#539)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt

Remove Start/FinishDiscoverableEvent
Fix to send event return results
Add DiscoverableStartResult

Missing event when you receive a duplicate directive quickly in BluetoothAgent

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

When resume player, attachment not used anymore.
So, consume it and remove immediately.

Release resources when not used (#582)

---

nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/AttachmentMessageRequest.kt

Remove byte array copy.
* from: ByteString.copyFrom()
* To: UnsafeByteOperations.unsafeWrap()
Remove AttachmentMessage's copy()

Remove byte array copy (#627)

---

app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt

wrap wakeup's value for context by double quotes(")

Fix wrong state value for context (#652)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt

To know about current request's detail, SpeechRecognizer.start return request object
When ExpectSpeech handling failure, try to close session if match with
current request.

Close session if occur error

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

the behavior when resume btn pressed at background focus should be same
when sent resume event.
So, we request focus again.

Determine behavior for resume btn

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

While collect context, current item can be changed.
So keep current item to send event before collect context.

Fix thread issue

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt

Using referrerDialogRequestId for ResponseTimeout, ListeningTimeout
event.
before: ExpectSpeech's dialogRequestId
after: Recognize's dialogRequestId

Fix wrong referrerDialogRequestId (#681)

---

nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt

#686 
1. FLAG_ACTIVITY_SINGLE_TOP is unused flag
2. FLAG_ACTIVITY_SINGLE_TOP is already set in the manifest
[In the source](https://github.com/nugu-developers/nugu-android/blob/master/nugu-login-kit/src/main/AndroidManifest.xml#L15)
```xml
<activity
android:name="com.skt.nugu.sdk.platform.android.login.auth.NuguOAuthCallbackActivity"
android:excludeFromRecents="true"
android:exported="true"
android:launchMode="singleTop"
android:noHistory="true"
android:theme="@style/Nugu.NoDisplay">
```

Remove intent flag when starting NuguOAuthCallbackActivity

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt

* ensure insertion order : use SingleThreadExecutor
* remove unused stopForegroundActivity API

Ensure execution order for FocusManager (#703)

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt

when stream closed, should return negative value.

Fix read's return value

---

app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultLocationAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/DefaultBatteryAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/MediaPlayerAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextState.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/OsContextProvider.kt

Change setState API interface to check equality of state at context
manager.
before: Each agent is responsible for optimizing context updates.
after: Each agent just pass context, then manager will update
optimally.

Improve context update interface (#752)

---

gradle.properties

ref: https://docs.gradle.org/6.0.1/release-notes.html
=> Publication of SHA256 and SHA512 checksums

Fix publish error

---

nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Directive.kt

Not thread-safe
* Direcitve's toString()
Do not override toString().
also, not efficient (directive is immutable class)

Fix crash (#766)

---

nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt

At SpeechRecognizerAggregator,
Prevent "startListeningWithTrigger" from being called while active.

Fix SpeechRecognizerAggregator's issue (#785)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractDirectiveHandler.kt

The class is easy to use incorrectly.
The implementer should call removeDirective() after finish handle.
<= An error-prone point.
So, wrap result object to remove directive from map.

Improve AbstractDirectiveHandler (#820)

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/utils/LoopThread.kt

Problem
1. onLoop() finished.
2. not enter waiting yet.
3. client call wakeXXX() to run onLoop(), but not work.
4. enter waiting.
Solution
If notify called at not waiting, skip wait.

Fix synchronization issue for LoopThread (#833)

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt

Issue
(A) EPD STARTED
(A) EPD STOPPED
(A) EPD send stop event (not receive response yet)
(B) EPD STARTED
the timeout occur for step 3 and (B) EPD handled as error.
<= this is problem. the (B) EPD working still...
Solve
At step 5, we should ignore the timeout event.
We don't care about the response for step 3's event

Fixed issue where epd does not stop #1010

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/Channel.kt
nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt

Even if the request channel has higher priority than foreground channel,
get background focus due to another higher priority channels exist.

Improve focus management #1032

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt

When ASR canceled before speech start,
send missing StopRecognizer event.

Send missing StopRecognize event #1037

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

If duration is null, do not seek.

Prevent calls when seek is not possible #1041

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt

Issue
1. Receive TTS.Speak, ASR.ExpectSpeech
2. TTS.Speak start and finish.
3. ASR.ExpectSpeech start, but canceled
since TTS.Speak's focus not released yet

Fix ASR.ExpectSpeech canceled by tts' focus #1050

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt

Some PlayContext does not affect a persistent rule.

Apply the flag to handle exception #1121

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerImpl.kt
nugu-core/src/test/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerTest.kt

* Clear evaporatable layers when new display rendered
* Clear evaporatable layers when new play started
which is not match playServiceId

Update policy for display management #1152

---

nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer2.kt

* the AudioAttribute supported at Android 21 or above,
split class for backward compatibility.

Split NuguOpusPlayer #1408

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
app/src/main/java/com/skt/nugu/sampleapp/application/SampleApplication.kt
app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
app/src/main/java/com/skt/nugu/sampleapp/service/SampleAppService.kt
app/src/main/java/com/skt/nugu/sampleapp/service/SampleNotificationChannel.kt
app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingHeadWindow.kt
app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingView.kt
app/src/main/java/com/skt/nugu/sampleapp/service/floating/FlowTextView.kt
app/src/main/java/com/skt/nugu/sampleapp/utils/PreferenceHelper.kt
app/src/main/res/drawable-xhdpi/background_white_rect.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/item_floaing.xml
app/src/main/res/values/strings.xml
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/EmptyLyricsPresenter.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateViewModel.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt

Add ExternalViewRenderer interface in TemplateRenderer and apply to SampleApp
case)
Basically TemplateRenderer has dependency with Fragment.
So when user destroys activity during media template is viewing and media is playing,
media goes to be stopped even it is expected to be play continue with notification.
So TemplateRenderer need to know the other view renderer.
plus)
fix bug that lyrics not shown sometimes

Add ExternalViewRenderer Interface to support thing like MediaNotification

---

fastlane/Fastfile

Token type have to be updated always.
Change to file type.
A file is generated when build.

Change auth type in Firebase App Distribution

---

nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayTransport.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DirectivesService.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/PingService.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/BackOff.kt

- Rename eventMessageHeaders to pendingHeaders
- Rename handleConnectedIfNeeded to handleOnConnected
- Add 'who' parameter(onError) to check whether it is a PingService error or an EventsService error
- **Change from disconnect to channel.enterIdle() in onRetry**
(https://github.com/grpc/grpc-java/issues/4056)

Improve gRPC connection for backoff and reconnect #1627

---

app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt

solution no.2 of
https://tde.sktelecom.com/pms/browse/OPENSDK-82
Change way to add Agent
main purpose :
Some agent needs provider (or client) and others none.
Previously a way to add agent is different by these two type.
Now it has combined but It may cause uncomfortable to POC already serviced because It changed to call two functions.
So It changed again for letting POC to call just one function to add agent.

Way to add agent - change setProvider() method name to enable**()

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt

before:
handlePlaybackCompleted()
->playSyncManager.release()
->at executor(onGranted())
->at executor(onPlaybackStopped())
after:
handlePlaybackCompleted()
->playSyncManager.release()
->at executor(onPlayerStopped())
-> atexecutor(onGranted())
onPlayerStopped() should be called before onGranted()
because, playDirectiveController's waitPlayExecuteInfo member should be
cleared, before onGranted called.

Fix AudioPlayer's focus not canceled #1729

---

nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
nugu-ux-kit/src/main/res/layout-land/view_display_audioplayer.xml
nugu-ux-kit/src/main/res/layout/fragment_template.xml
nugu-ux-kit/src/main/res/layout/view_display_audioplayer.xml
nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml

-Apply delay to removing template to avoid exposure of rear screen very short when transition occurs.
It is like a blink.
-Make media template background transparent to do not cover rear screen when it is collapsed mode.

Apply delay to removing template to avoid exposure of rear screen very short.

---

nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt

[COSTELTV-24](https://tde.sktelecom.com/pms/browse/COSTELTV-24?filter=-3)
When using webview for Media on poc such as nu300, media status info not saved before. 
This PR fixed this issue

Save mediaState when config changed

---

app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt

* Sometimes, player gets previous music stream from local cache.

Fix ExoMediaPlayer(Sample) cacheKey update order (COSTELTV-76)

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt

* To know when the context was requested

Add debug log

---

nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateMediaHandler.kt
nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateMediaHandlerTest.kt

issue : When Media Template shown on PAUSE state, progress is 0. It's because progress is notified only PLAY state
*Template designed to be alive during media active(Playing, pause) state originally.  But special case coming up that template destroyed and recreated during active state. 
[APOLLOTF-354](https://tde.sktelecom.com/pms/browse/APOLLOTF-354)

Notify media progress when duration retrieved

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/ProgressTimer.kt

Problem
* If the time when 'onProgressReportDelay' is called and the time at which the audio playback ends are same,
ProgressTimer may be canceled rarely.
Solve
* A finish() API was added to ensure onProgressReportDelay()'s call.

Fix onProgressReportDelay not called rarely. #2246

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/UpdateDirectiveHandler.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/BlockingPolicy.kt

* The render/update directive blocks the execution of directive with a "blocked by=VISUAL" policy.

Apply "visual" blocking policy #2294

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt

* apply when no TTS.SPEAK directive.

Fix muteDelay apply condition

---

nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
nugu-ux-kit/src/main/res/layout/nugu_fragment_playlist.xml

reason: onMove callback on ItemTouchHelper must return true after Adapter updated. But It wasn't. Because the process occurs asynchronously. 
solution:  Change onMove callback to update Adapter directly and then return true.

Fix weird fast scrolling when dragging first item on playlist.

---

nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateExtension.kt
nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateExtensionTest.kt

Originally the code below was there in updateImage() function.
`visibility = if (url != null) View.VISIBLE else View.GONE`
But when I did Playlist implementation, I thought It is not necessary and removed it. 
And It makes side effect now, so I recover it.

Fix right top image not visible when adult only music playing

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt

* If EPD's timeout is longer than request(ASR.Recognize Event)'s timeout, the ASR is not working.
* In this case, send request after start speech.

Deferred ASR.Recognize Event #2452

---

nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/ClientChannel.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayTransport.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DirectivesService.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/DirectivePreconditions.kt
nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClientTest.kt
nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsServiceTest.kt
nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/DirectivePreconditionsTest.kt
nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/AsyncKey.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Call.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageSender.kt
nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/FixedStateCall.kt

Implement the eventListener
``` kotlin
messageSender.newCall(request)
.enqueue(
callback = { ... },
eventListener = object : MessageSender.EventListener {
override fun onAsyncKeyReceived(
request: MessageRequest, asyncKey: AsyncKey
) {
TODO("Not yet implemented")
}
})
```

Add an asyncKey listener to the directive paylaod on the device-gateway client. #2470

---

nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt

* Even if finish ASR, async's response(directives) will be arrived on event channel. To cancel(close) this channel, add API at Request.

Cancel ASR's Recognize event after ASR finished. #2506

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt

* Fix a shouldBeAcquired condition correctly. 
* if the condition is false, continue to set foreground focus.

Fix on focus acquire failed #2517

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt

* If failed to acquire external focus, the channelToAcquire's focus should be 'Background'.

Fix side effect of issue-2517

---

nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt

* When failed to acquire external focus, set channel's focus on BACKGROUND

Improve FocusManger's focus handling #2537
